matrix:
  include:
    - os: linux
      sudo: required
      dist: focal
      compiler: gcc
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
    - os: linux
      sudo: required
      dist: xenial
      compiler: gcc
    - os: osx
      osx_image: xcode10.3

language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
# SDL1.2 specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libsdl1.2-dev; fi
# End of SDL1.2 specific part
#-----------------------
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - git clone https://github.com/quicky2000/lib_gif.git
  - git clone https://github.com/quicky2000/parameter_manager.git
  - git clone https://github.com/quicky2000/quicky_exception.git
  - git clone https://github.com/quicky2000/simple_gui.git
  - git clone https://github.com/quicky2000/quicky_utils.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then generate_makefile gif_player ; make ; cd $MY_LOCATION; mkdir cmake_build ; cd cmake_build ; fi
  - cmake $QUICKY_REPOSITORY/gif_player
  - make
#EOF
